### ISSUE TITLE
[bug] To text table align not correct for Chinese

### ISSUE THREAD

**Issue by jiming** [fitnr/SublimeDataConverter#21]
Dear fitnr,

Thanks for the great plugin.

When I convert to **text table**,  **gherkin** or **Markdown(github flavored)**, the align is not correct
````
id,name,age
1,jiming,20
2,cb,5
3,张三丰峰峰,5
4,jackson apache,5
````

will be convert to 
````
+----+----------------+-----+
| id | name           | age |
+----+----------------+-----+
| 1  | jiming         | 20  |
| 2  | cb             | 5   |
| 3  | 张三丰峰峰          | 5   |
| 4  | jackson apache | 5   |
+----+----------------+-----+
````

**Comment by fitnr** [comment]
This is a known issue. It also applies to characters like Emoji and Cuneiform.

The problem is that Chinese characters aren't the same visual width as the Latin ones. Looking into it an little, one possible solution would be to map all the Latin characters in a column containing ideographic characters to their [fullwidth forms](https://en.wikipedia.org/wiki/Halfwidth_and_fullwidth_forms#Block).

So the result of your example would be something like this:
````
+----+－－－－－－－－－－－－－－－－+-----+
| id |　ｎａｍｅ　　　　　　　　　　　| age |
+----+－－－－－－－－－－－－－－－－+-----+
| 1  |　ｊｉｍｉｎｇ　　　　　　　　　| 20  |
| 2  |　ｃｂ　　　　　　　　　　　　　| 5   |
| 3  |　张三丰峰峰　　　　　　　　　　| 5   |
| 4  |　ｊａｃｋｓｏｎ　ａｐａｃｈｅ　| 5   |
+----+－－－－－－－－－－－－－－－－+-----+
````

As you can see, it's a bit visually jarring, since the fullwidth Roman characters are pretty different from their halfwidth counterparts, especially the hyphen (`-`). Any column with CJK characters would need to be entirely full-width, since one can't rely on any particular width ratio between the two types of characters.

A little more work would also be needed to correctly handle diacretics.

I would probably add this as an option that defaults to off, since it would have the possibility of munging some truly esoteric input.

**Comment by fitnr** [comment]
I've added a draft of the feature to the branch [fullwidth](https://github.com/fitnr/SublimeDataConverter/tree/fullwidth). Could you pull it and do a little beta testing with it? (Uninstall the package in ST, download it as a zip, expand it, then place it in your Packages directory.) I don't have test suits set up in this package, :)

**Comment by jiming** [comment]
Hi Neil,

Thank you for the quick fixed version. 

I tried SublimeDataConverter-fullwidth.zip, but it is still not working.

Perhaps you could try use following function to check chinese character and set it length as 2.

`
def is_chinese_char(i):
    return 0x4e00<=ord(i)<0x9fff
`

What do you think!

Thanks!
Jiming

**Comment by fitnr** [comment]
Sorry, I forgot one step in my instructions: All the following to the settings file (Preferences > Package Settings > DataConverter > User Settings):
```
"use_fullwidth": true
```

I've made the routine optional since it requires an extra loop through the data.

I'm using [`unicodedata.east_asian_width`](https://docs.python.org/3.5/library/unicodedata.html#unicodedata.east_asian_width) to detect wide characters.

**Comment by jiming** [comment]
Dear Neil,

Good news is that the align is working. Bad news is that it changed English character to double byte character.

```
+----+－－－－－－－－－－－－－－－－+-----+
| id |　ｎａｍｅ　　　　　　　　　　　| age |
+----+－－－－－－－－－－－－－－－－+-----+
| 1  |　ｊｉｍｉｎｇ　　　　　　　　　| 20  |
| 2  |　ｃｂ　　　　　　　　　　　　　| 5   |
| 3  |　张三丰峰峰　　　　　　　　　　| 5   |
| 4  |　ｊａｃｋｓｏｎ　ａｐａｃｈｅ　| 5   |
+----+－－－－－－－－－－－－－－－－+-----+

```

**Comment by fitnr** [comment]
That's the expected result. Despite the fact that they're called "halfwidth and fullwidth forms," many fonts don't display characters as twice as wide as letters. Further research shows that Chinese fonts tend to respect the 2:1 ratio.

I've now added a different check and fullwidth ideographs will be treated as twice as wide Roman letters. So the result will be:
````
+----+----------------+-----+
| id | name           | age |
+----+----------------+-----+
| 1  | jiming         | 20  |
| 2  | cb             | 5   |
| 3  | 张三丰峰峰     | 5   |
| 4  | jackson apache | 5   |
+----+----------------+-----+
````
This doesn't look good in the default Github fixed-width font, but looks OK in a font like SimHei Regular:

![screen shot 2017-05-16 at 10 46 33 am](https://cloud.githubusercontent.com/assets/714125/26112130/fc4106a6-3a24-11e7-8993-96e60c30c69a.png)

You can see this in the branch [checkwide](https://github.com/fitnr/SublimeDataConverter/tree/checkwide).

**Comment by jiming** [comment]
Dear Neil,

I am sorry that I might not make myself clear.  In the example I posted. The "ｎａｍｅ" is not "name". They are not same character.

It's wired that in your example, the "name" is "name". So I guess the function you used to process string might behave different in Chinse OS.

I think perhaps you converted the original charater before calculate its lenght. And then using the converted character as the final result. Is that possible?

Thanks!
Jiming

**Comment by fitnr** [comment]
You did make yourself clear, and I rewrote the code to respond to the issue you raised. I used the update in the branch [checkwide](https://github.com/fitnr/SublimeDataConverter/tree/checkwide) to generate the example in the image above. I'm sure it does exactly what you want.

**Comment by jiming** [comment]
Dear Neil, thank you very much. I will try when you released it.
